name: CI Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
            node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - run: echo "Building in $NODE_ENV node"   
      - run: echo "${{ secrets.GITHUB_TOKEN }}"   
