name: Build Multiple Environments

on:
  push:
    branches:
        - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}    

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0     
     
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform    

      - name: Terraform plan
        run: terraform plan
        working-directory: ./terraform    
        
      - name: Terraform apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-aprove
        working-directory: ./terraform